# Generated by Django 4.2.5 on 2023-09-20 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=30, verbose_name="Название урока"),
                ),
                ("url", models.URLField(verbose_name="ссылка на видео")),
                (
                    "total_time",
                    models.IntegerField(verbose_name="Длительность урока в секундах"),
                ),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=40, verbose_name="навзание продукта"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="UserProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesson.product",
                        verbose_name="продукт",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователь_продукт",
                "verbose_name_plural": "пользователи_продукты",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="UserLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_last",
                    models.DateField(auto_created=True, verbose_name="Дата просмотра"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Не просмотрено"), ("2", "Просмотрено")],
                        default=1,
                        max_length=1,
                    ),
                ),
                ("time", models.IntegerField(verbose_name="Время просмотра.")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesson.lesson",
                        verbose_name="урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователь_урок",
                "verbose_name_plural": "пользователи_уроки",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="ProductLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesson.lesson",
                        verbose_name="урок",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesson.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт_урок",
                "verbose_name_plural": "продукты_уроки",
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="product",
            field=models.ManyToManyField(
                through="lesson.ProductLesson", to="lesson.product"
            ),
        ),
    ]
