# Generated by Django 4.2.5 on 2023-09-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userlesson",
            constraint=models.UniqueConstraint(
                fields=("user", "lesson"), name="unique_user_lesson_userlesson"
            ),
        ),
        migrations.AddConstraint(
            model_name="userproduct",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="unique_user_product_userproduct"
            ),
        ),
    ]
