# Generated by Django 4.2.5 on 2023-09-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0003_remove_userlesson_status_alter_userlesson_date_last"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Название урока"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="url",
            field=models.URLField(unique=True, verbose_name="ссылка на видео"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=40, unique=True, verbose_name="навзание продукта"
            ),
        ),
        migrations.AlterField(
            model_name="userlesson",
            name="date_last",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата просмотра"),
        ),
        migrations.AlterField(
            model_name="userlesson",
            name="time",
            field=models.IntegerField(default=0, verbose_name="Время просмотра."),
        ),
    ]
