# Generated by Django 4.2.5 on 2023-09-21 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0004_alter_lesson_title_alter_lesson_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productlesson",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_lesson",
                to="lesson.product",
                verbose_name="продукт",
            ),
        ),
        migrations.AlterField(
            model_name="userproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_product",
                to="lesson.product",
                verbose_name="продукт",
            ),
        ),
    ]
