# Generated by Django 4.2.5 on 2023-09-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0005_alter_productlesson_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productlesson",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_lesson",
                to="lesson.lesson",
                verbose_name="урок",
            ),
        ),
        migrations.AlterField(
            model_name="userlesson",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userlesson",
                to="lesson.lesson",
                verbose_name="урок",
            ),
        ),
    ]
