# Generated by Django 4.2.5 on 2023-09-21 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lesson", "0006_alter_productlesson_lesson_alter_userlesson_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productlesson",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="lesson.lesson",
                verbose_name="урок",
            ),
        ),
        migrations.AlterField(
            model_name="productlesson",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="lesson.product",
                verbose_name="продукт",
            ),
        ),
        migrations.AlterField(
            model_name="userlesson",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="lesson.lesson",
                verbose_name="урок",
            ),
        ),
        migrations.AlterField(
            model_name="userlesson",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="userproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="lesson.product",
                verbose_name="продукт",
            ),
        ),
        migrations.AlterField(
            model_name="userproduct",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
