# Generated by Django 4.2.5 on 2023-10-14 19:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Название урока"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(unique=True, verbose_name="ссылка на видео"),
                ),
                (
                    "video_duration",
                    models.IntegerField(
                        default=0, verbose_name="Длительность урока в секундах"
                    ),
                ),
                ("products", models.ManyToManyField(to="catalog.product")),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="LessonViewInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("VIEWED", "Viewed"), ("NOT_VIEWED", "Not Viewed")],
                        default="NOT_VIEWED",
                        max_length=30,
                    ),
                ),
                (
                    "view_time",
                    models.IntegerField(default=0, verbose_name="Время просмотра"),
                ),
                (
                    "last_view_datetime",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 10, 14, 22, 37, 14, 235355)
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="study.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "unique_together": {("lesson", "user")},
            },
        ),
    ]
